version: '3.4'

services:
  egdebookingsystem:
    image: egdebookingsystem:dev
    container_name: EgdeBookingSystem
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "EgdeBookingSystem"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\nerga\Bachelor\dockerTest\Go4IT\EgdeBookingSystem:/app
      - C:\Users\nerga\Bachelor\dockerTest\Go4IT\EgdeBookingSystem:/src
      - C:\Users\nerga\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\nerga\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/EgdeBookingSystem.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true